//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid ItemId { get; set; }
        public int CategoryId { get; set; }
        public string ZoneName { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public decimal ItemPrice { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ItemDetailId { get; set; }
        public string TabName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
    }
}
